### ISSUE TITLE
Implement DynamoDB Template

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack#12]
The Goldstack [S3 Template](https://docs.goldstack.party/docs/modules/s3) provides a way for application to persist data on AWS S3. However, while S3 is a good place to store files, binary data and simple structured data, it is not easy to query data on S3.

Thus it would be good to add another persistence option to Goldstack that is based on a database. This should ideally be fully serverless, so runs at minimal base costs and can scale up as required. [Aurora Serverless v2](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-2.html) looks like a viable option, ~but it is still only in preview~ - [Aurora Serverless v2 is not generally avalable as of 21st of April 2022](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-aurora-serverless-v2/). Aurora Serverless v1 does not seem like a good option due to cold start times.

Thus only remaining option maybe [DynamoDB](https://aws.amazon.com/dynamodb/) - I generally prefer DBs based on SQL, but I think therer is just no other option available at present.

---

## Dynamo DB Solution Design

- Local testing with [DynamoDB Local provided by AWS](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html), possibly run with [testcontainers-node](https://github.com/testcontainers/testcontainers-node)
- Terraform [dynamodb_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table) resource, possibly create DynamoDB table in code and pull in DynamoDB tables using [data](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/dynamodb_table) to configure IAM.
- Ensure that table is created during cold start of lambdas and run migrations through [east-dynamodb](https://github.com/cstar-industries/east-dynamodb) - this must also work with the local DynamoDB.
- Options for working with data
  - SQL interface for dynamodb https://abba.dev/blog/dynamodb-partiql-javascript
  - [dynamoose](https://dynamoosejs.com/getting_started/Introduction) - [supports single-table data modelling from v2](https://github.com/dynamoose/dynamoose/issues/709) - see also [StackOverflow answer](https://stackoverflow.com/a/64974754/270662)
  - [typedorm](https://github.com/typedorm/typedorm/blob/main/docs/guide.md)
  - [DynamoDB Toolbox](https://github.com/jeremydaly/dynamodb-toolbox)
  - [dynamodb-data-mapper-js](https://github.com/awslabs/dynamodb-data-mapper-js) which maybe [unmaintained](https://github.com/awslabs/dynamodb-data-mapper-js/issues/201)
  - [dynamodb-easy](https://github.com/shiftcode/dynamo-easy) - provides [no native support for single-table data modelling](https://github.com/shiftcode/dynamo-easy/issues/341)

## Tasks

- [x] Set up basic module API
- [x] Support local testing
- [x] Support migrations
- [x] Support infra deployment to AWS
- [x] Set up deploy set
- [x] Create template page
- [x] Create Readme
- [x] Create documentation page
- [x] Create boilerplate
- [x] Create sample project
- [x] Write blog post

**Comment by mxro** [comment]
Looks like [`east`](https://github.com/okv/east/issues/93) may not allow to directly reference migrations and configuration, which would make it difficult to run this in the Lambda function. Instead, will have a look at [umzug](https://github.com/sequelize/umzug) and [dynamodb-migrations-tool](https://www.npmjs.com/package/dynamodb-migrations-tool)
